"""
Forecasting Service for CargoPredict.
Connects the FastAPI forecast endpoints directly to the real XGBoost ML Engine
and queries ml.ml_freight_daily in Supabase PostgreSQL.
"""
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
from app.db import execute_dict_query
from app.services.ml_engine import MLForecastEngine

DISCLAIMER = (
    "Forecasts are generated by trained multi-horizon XGBoost gradient boosted decision tree models "
    "operating over historical maritime corridor observations from Supabase PostgreSQL (ml.ml_freight_daily)."
)


class FreightForecastingService:
    @staticmethod
    def get_available_routes() -> List[Dict[str, Any]]:
        """Fetch distinct route definitions and vessel classes from route master and ml dataset."""
        sql = """
            SELECT 
                r.route_id, 
                r.origin_port_id, 
                p1.port_name as origin_port_name,
                p1.country as origin_country,
                r.destination_port_id, 
                p2.port_name as destination_port_name,
                p2.country as destination_country,
                r.distance_nm, 
                r.cargo_type, 
                r.vessel_class
            FROM reference.route_master r
            LEFT JOIN reference.port_master p1 ON r.origin_port_id = p1.port_id
            LEFT JOIN reference.port_master p2 ON r.destination_port_id = p2.port_id
            ORDER BY r.route_id;
        """
        return execute_dict_query(sql)

    @staticmethod
    def get_historical_freight(
        route_id: str = "R001",
        vessel_class: Optional[str] = None,
        days: int = 180
    ) -> List[Dict[str, Any]]:
        """Fetch recent historical daily series from ml.ml_freight_daily."""
        params = [route_id]
        vessel_clause = ""
        if vessel_class:
            vessel_clause = "AND vessel_class = %s"
            params.append(vessel_class)
        params.append(days)

        sql = f"""
            SELECT 
                date,
                route_id,
                vessel_class,
                cargo_type,
                freight_rate_usd_per_mt,
                bdi_proxy,
                vlsfo_singapore_usd_per_mt,
                usd_inr,
                congestion_score,
                vessels_waiting,
                available_vessel_count,
                freight_rolling_mean_7,
                freight_rolling_std_7,
                is_synthetic
            FROM ml.ml_freight_daily
            WHERE route_id = %s {vessel_clause}
            ORDER BY date DESC
            LIMIT %s;
        """
        rows = execute_dict_query(sql, tuple(params))
        rows.reverse()  # Return in chronological order
        return rows

    @staticmethod
    def generate_forecast(
        route_id: str = "R001",
        vessel_class: Optional[str] = None,
        cargo_type: Optional[str] = "Coking Coal",
        horizon_days: int = 14,
        fuel_price_shift_pct: float = 0.0,
        congestion_shift_pct: float = 0.0,
        vessel_supply_shift_pct: float = 0.0
    ) -> Dict[str, Any]:
        """
        Invokes the real XGBoost ML Engine for 14d, 30d, or 90d forecasting.
        Calculates confidence intervals and scenario sensitivities directly through model inference.
        """
        if horizon_days not in (14, 30, 90):
            if horizon_days <= 20:
                horizon_days = 14
            elif horizon_days <= 60:
                horizon_days = 30
            else:
                horizon_days = 90

        # Determine effective vessel class from route if not explicitly supplied
        effective_vessel = vessel_class
        if not effective_vessel:
            routes = FreightForecastingService.get_available_routes()
            for r in routes:
                if r["route_id"] == route_id:
                    effective_vessel = r.get("vessel_class") or "Capesize"
                    break
            if not effective_vessel:
                effective_vessel = "Capesize"

        # 1. Fetch recent history for charting
        hist_records = FreightForecastingService.get_historical_freight(
            route_id=route_id,
            vessel_class=effective_vessel,
            days=90
        )

        # 2. Invoke XGBoost ML Engine
        ml_engine = MLForecastEngine.get_instance()
        ml_result = ml_engine.predict(
            route_id=route_id,
            vessel_class=effective_vessel,
            cargo_type=cargo_type or "Coking Coal",
            horizon=horizon_days,
            bunker_vlsfo_delta_pct=fuel_price_shift_pct,
            congestion_delta_pct=congestion_shift_pct,
            vessel_supply_delta_pct=vessel_supply_shift_pct
        )

        base_rate = ml_result["current_spot_rate"]
        predicted_final_rate = ml_result["predicted_rate"]

        # 3. Format daily points for chart display
        obs_date = datetime.strptime(ml_result["observation_date"][:10], "%Y-%m-%d").date()
        forecast_points = []
        for step in range(1, horizon_days + 1):
            target_date = obs_date + timedelta(days=step)
            progress = step / float(horizon_days)
            # Smooth trajectory towards ML predicted final rate
            step_rate = round(base_rate + (predicted_final_rate - base_rate) * progress, 2)
            rmse = ml_result["empirical_rmse"]
            scale = (progress ** 0.5)

            forecast_points.append({
                "date": target_date.isoformat(),
                "day_index": step,
                "predicted_rate_usd_per_mt": step_rate,
                "baseline_rate_usd_per_mt": round(base_rate, 2),
                "scenario_impact_usd": round(step_rate - base_rate, 2),
                "ci_80_lower": round(max(5.0, step_rate - 1.28 * rmse * scale), 2),
                "ci_80_upper": round(step_rate + 1.28 * rmse * scale, 2),
                "ci_95_lower": round(max(4.0, step_rate - 1.96 * rmse * scale), 2),
                "ci_95_upper": round(step_rate + 1.96 * rmse * scale, 2),
            })

        # Summary KPIs
        rates = [p["predicted_rate_usd_per_mt"] for p in forecast_points]
        avg_predicted = round(sum(rates) / len(rates), 2)
        min_predicted = min(rates)
        max_predicted = max(rates)

        return {
            "route_id": route_id,
            "vessel_class": effective_vessel,
            "cargo_type": cargo_type,
            "as_of_date": ml_result["observation_date"],
            "current_rate_usd_per_mt": base_rate,
            "current_spot_rate": base_rate,
            "predicted_rate_usd_per_mt": predicted_final_rate,
            "predicted_rate": predicted_final_rate,
            "horizon_days": horizon_days,
            "model_name": ml_result["model_name"],
            "p10": ml_result["p10"],
            "p50": ml_result["p50"],
            "p90": ml_result["p90"],
            "ci_lower": ml_result["ci_lower"],
            "ci_upper": ml_result["ci_upper"],
            "kpis": {
                "latest_rate": base_rate,
                "average_forecast": avg_predicted,
                "min_forecast": min_predicted,
                "max_forecast": max_predicted,
                "projected_change_pct": ml_result["rate_delta_pct"],
                "volatility_score": round(ml_result["empirical_rmse"], 2)
            },
            "scenario_adjustments": ml_result["scenario_applied"],
            "forecast": forecast_points,
            "trajectory": forecast_points,
            "recent_history": hist_records[-30:],
            "disclaimer": DISCLAIMER
        }
